# Generated by Django 6.0.5 on 2026-05-18 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_min', models.FloatField(verbose_name='蛋身高最小值(m)')),
                ('height_max', models.FloatField(verbose_name='蛋身高最大值(m)')),
                ('weight_min', models.FloatField(verbose_name='蛋体重最小值(kg)')),
                ('weight_max', models.FloatField(verbose_name='蛋体重最大值(kg)')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_data', to='pets.pet', verbose_name='精灵')),
            ],
            options={
                'verbose_name': '孵蛋数据',
                'verbose_name_plural': '孵蛋数据',
            },
        ),
        migrations.CreateModel(
            name='EggTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_uid', models.CharField(max_length=50, verbose_name='游戏UID')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('active', '活跃'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_trades', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '交换信息',
                'verbose_name_plural': '交换信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EggTradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('offer', '我拥有'), ('want', '我想要')], max_length=10, verbose_name='类型')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_items', to='pets.pet', verbose_name='精灵蛋')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eggs.eggtrade', verbose_name='所属交换')),
            ],
            options={
                'verbose_name': '交换条目',
                'verbose_name_plural': '交换条目',
            },
        ),
    ]
