# Generated by Django 6.0.5 on 2026-05-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0001_initial'),
        ('pets', '0003_remove_pet_egg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100, verbose_name='蛋图片文件名')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='egg_image', to='pets.pet', verbose_name='精灵')),
            ],
            options={
                'verbose_name': '蛋图片',
                'verbose_name_plural': '蛋图片',
            },
        ),
    ]
