# Generated by Django 6.0.5 on 2026-05-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='蛋组名称')),
            ],
            options={
                'verbose_name': '蛋组',
                'verbose_name_plural': '蛋组',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='属性名称')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标文件名')),
            ],
            options={
                'verbose_name': '属性',
                'verbose_name_plural': '属性',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='编号')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('ability_name', models.CharField(blank=True, max_length=100, verbose_name='特性名称')),
                ('ability_effect', models.TextField(blank=True, verbose_name='特性效果')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('height_min', models.FloatField(verbose_name='身高最小值(m)')),
                ('height_max', models.FloatField(verbose_name='身高最大值(m)')),
                ('weight_min', models.FloatField(verbose_name='体重最小值(kg)')),
                ('weight_max', models.FloatField(verbose_name='体重最大值(kg)')),
                ('hp', models.IntegerField(verbose_name='生命')),
                ('physical_attack', models.IntegerField(verbose_name='物攻')),
                ('magical_attack', models.IntegerField(verbose_name='魔攻')),
                ('physical_defense', models.IntegerField(verbose_name='物防')),
                ('magical_defense', models.IntegerField(verbose_name='魔防')),
                ('speed', models.IntegerField(verbose_name='速度')),
                ('image', models.CharField(blank=True, max_length=100, verbose_name='图片文件名')),
                ('ability_icon', models.CharField(blank=True, max_length=100, verbose_name='特性图标文件名')),
                ('distribution', models.CharField(blank=True, max_length=200, verbose_name='分布地区')),
                ('form', models.CharField(blank=True, max_length=50, verbose_name='形态')),
                ('is_final', models.BooleanField(default=False, verbose_name='是否为最终形态')),
                ('egg_groups', models.ManyToManyField(blank=True, related_name='pets', to='pets.egggroup', verbose_name='蛋组')),
                ('elements', models.ManyToManyField(related_name='pets', to='pets.elementtype', verbose_name='属性')),
            ],
            options={
                'verbose_name': '精灵',
                'verbose_name_plural': '精灵',
                'ordering': ['number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('category', models.CharField(choices=[('物攻', '物攻'), ('魔攻', '魔攻'), ('防御', '防御'), ('状态', '状态')], max_length=10, verbose_name='类别')),
                ('power', models.IntegerField(default=0, verbose_name='威力')),
                ('energy_cost', models.IntegerField(default=0, verbose_name='能耗')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标文件名')),
                ('description', models.TextField(blank=True, verbose_name='效果描述')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pets.elementtype', verbose_name='属性')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PetSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_level', models.IntegerField(blank=True, null=True, verbose_name='学习等级')),
                ('learn_method', models.CharField(choices=[('升级', '升级'), ('血脉技能', '血脉技能'), ('技能石', '技能石')], max_length=20, verbose_name='学习方式')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_skills', to='pets.pet', verbose_name='精灵')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_skills', to='pets.skill', verbose_name='技能')),
            ],
            options={
                'verbose_name': '精灵技能',
                'verbose_name_plural': '精灵技能',
                'ordering': ['learn_method', 'learn_level'],
            },
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='进化条件')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='所需等级')),
                ('pet_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_to', to='pets.pet', verbose_name='进化前')),
                ('pet_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_from', to='pets.pet', verbose_name='进化后')),
            ],
            options={
                'verbose_name': '进化链',
                'verbose_name_plural': '进化链',
                'unique_together': {('pet_from', 'pet_to')},
            },
        ),
        migrations.CreateModel(
            name='TypeMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField(verbose_name='倍率')),
                ('attacking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_matchups', to='pets.elementtype', verbose_name='攻击方属性')),
                ('defending_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_matchups', to='pets.elementtype', verbose_name='防御方属性')),
            ],
            options={
                'verbose_name': '属性克制',
                'verbose_name_plural': '属性克制',
                'unique_together': {('attacking_type', 'defending_type')},
            },
        ),
    ]
