# Generated by Django 6.0.5 on 2026-05-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='egg_image',
            field=models.CharField(blank=True, max_length=100, verbose_name='蛋的图片文件名'),
        ),
    ]
