# Generated by Django 6.0.5 on 2026-05-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_egg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='egg_image',
        ),
    ]
