# Generated by Django 6.0.6 on 2026-07-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0004_alter_pet_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='阵容名称')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('is_popular', models.BooleanField(default=False, help_text='勾选后在敌方热门阵容下拉中可选', verbose_name='热门阵容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '阵容模板',
                'verbose_name_plural': '阵容模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='位置 (1-6)')),
                ('level', models.PositiveSmallIntegerField(default=60, verbose_name='等级')),
                ('star', models.PositiveSmallIntegerField(default=5, verbose_name='星级')),
                ('growth', models.PositiveSmallIntegerField(default=0, verbose_name='成长')),
                ('talent_hp', models.PositiveSmallIntegerField(default=5)),
                ('talent_pa', models.PositiveSmallIntegerField(default=5)),
                ('talent_ma', models.PositiveSmallIntegerField(default=5)),
                ('talent_pd', models.PositiveSmallIntegerField(default=5)),
                ('talent_md', models.PositiveSmallIntegerField(default=5)),
                ('talent_sp', models.PositiveSmallIntegerField(default=5)),
                ('nature_up', models.CharField(blank=True, choices=[('', '无'), ('hp', '生命'), ('physical_attack', '物攻'), ('magical_attack', '魔攻'), ('physical_defense', '物防'), ('magical_defense', '魔防'), ('speed', '速度')], default='', max_length=20)),
                ('nature_down', models.CharField(blank=True, choices=[('', '无'), ('hp', '生命'), ('physical_attack', '物攻'), ('magical_attack', '魔攻'), ('physical_defense', '物防'), ('magical_defense', '魔防'), ('speed', '速度')], default='', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pvp_assistant.teamtemplate')),
            ],
            options={
                'verbose_name': '阵容精灵',
                'verbose_name_plural': '阵容精灵',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TeamPetSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(verbose_name='技能槽 (1-4)')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.skill')),
                ('team_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pvp_assistant.teampet')),
            ],
            options={
                'verbose_name': '精灵技能',
                'verbose_name_plural': '精灵技能',
                'ordering': ['slot'],
                'unique_together': {('team_pet', 'slot')},
            },
        ),
    ]
