# Generated by Django 6.0.5 on 2026-07-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampet',
            name='talent_hp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teampet',
            name='talent_ma',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teampet',
            name='talent_md',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teampet',
            name='talent_pa',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teampet',
            name='talent_pd',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teampet',
            name='talent_sp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
